FROM ruby:3.2.8-alpine

ARG WORKDIR=/app

ENV RUNTIME_PACKAGES="nodejs tzdata postgresql-dev postgresql git yaml-dev" \
    DEV_PACKAGES="build-base curl-dev" \
    HOME=/${WORKDIR} \
    LANG=C.UTF-8 \
    TZ=Asia/Tokyo \
    RAILS_ENV="development"

WORKDIR ${HOME}

COPY Gemfile* ./

RUN apk update && \
    apk upgrade && \
    apk add --no-cache ${RUNTIME_PACKAGES} && \
    apk add --virtual build-dependencies --no-cache ${DEV_PACKAGES} && \
    bundle install -j4 && \
    apk del build-dependencies

COPY . .

CMD ["bin/dev", "-b", "0.0.0.0", "-p", "${PORT:-10000}"]
