FROM ruby:3.2.8-alpine

ARG WORKDIR=/app

ENV RUNTIME_PACKAGES="nodejs npm tzdata yarn postgresql-dev git yaml-dev" \
DEV_PACKAGES="build-base" \
LANG=C.UTF-8 \
TZ=Asia/Tokyo \
RAILS_ENV=development

WORKDIR ${WORKDIR}

COPY Gemfile Gemfile.lock ./

RUN apk add --no-cache ${RUNTIME_PACKAGES} && \
apk add --no-cache --virtual build-deps ${DEV_PACKAGES} && \
bundle install -j4 && \
npm install -g npm && \
apk del build-deps

COPY . .

CMD ["sh", "-c", "rm -f tmp/pids/server.pid && ./bin/dev"]
